Improve README
austintgriffith/eth-hooks pull request #20
Opened 2021-07-13 14:13 UTC by talentlessguy

This PR re-formats the readme to be more readable. Also "Install" section is added for quick copypaste

2021-07-14 13:34 UTC, ShravanSunder requested changes

2021-07-14 13:34 UTC, ShravanSunder commented on README.md
> +npm install eth-hooks
this should be yarn, its what we use for eth hooks and scaffold eth

2021-07-14 13:40 UTC, talentlessguy commented on README.md
> +npm install eth-hooks
@ShravanSunder oops my bad, fixed this now

2021-07-18 06:39 UTC, talentlessguy commented
is everything good with the PR?

2021-07-18 13:12 UTC, ShravanSunder commented
Yes!  I will approve

2021-07-18 13:12 UTC, merged